name: Deploy Backend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      
      - name: Build Docker image
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/meetup-backend:latest .

      
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/meetup-backend:latest

      
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_HOOK_URL }}